package:
  name: larix
  version: {{ environ['VERSION'] }}


build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - VERSION

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
    - cmake

  run:
    - python
    - numpy
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/larix
  license:  Apache 2 license
  summary: 'Larix: is a set of data and image processing tools'
