name: larix_package

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # 18.04 supports CUDA 10.1+ (gxx <= 8)
          - os: ubuntu-18.04
            cuda: "10.1"
            gcc: 8
      max-parallel: 5
    env:
      build_dir: "build"
      config: "Release"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Decrypt large secret
      run: ./scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    # This command is just an example to show your secret being printed
    # Ensure you remove any print statements of your secrets. GitHub does
    # not hide secrets that use this workaround.
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/my_secret.json

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      working-directory: ${{ env.build_dir }}
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi

    - name: Install dependencies in conda environment
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install additional conda packages
      run: |
        conda install --yes numpy conda-build anaconda-client setuptools cython cmake

    - name: Building and installing larix package
      run: |
        conda config --set anaconda_upload no
        export VERSION=`date +%Y.%m`
        conda build recipe/ --numpy=1.15 --python=3.7
        conda install --channel /usr/share/miniconda/conda-bld/ larix --offline --override-channels

    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest

    #- name: Upload the package to conda cloud
    #  run: |
    #    chmod +x ./scripts/conda_upload.sh
    #    ./scripts/conda_upload.sh
